services:
  mongo:
    image: mongo
    container_name: mongo-local
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: ['--replSet', 'rs0', '--bind_ip_all']
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')", '--quiet']
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s

  mongo-init:
    image: mongo
    depends_on:
      mongo:
        condition: service_healthy
    command: mongosh --host mongo --eval "try{rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]})}catch(e){}"
    restart: 'no'

volumes:
  mongo-data:
